name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print welcome
        run: echo "Welcome to first workflow, job and step"
      - name: Print Goodbye
        value: echo "Done - bye!"
